-- MySQL Script generated by MySQL Workbench
-- dom 07 feb 2021 12:16:22 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema futbol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema futbol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futbol` ;
USE `futbol` ;

-- -----------------------------------------------------
-- Table `futbol`.`CLUB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`CLUB` (
  `Código club` VARCHAR(45) NOT NULL,
  `Nombre club` VARCHAR(45) NOT NULL,
  `Presidente` VARCHAR(45) NOT NULL,
  `Año fundado` INT NOT NULL,
  `Nº socios` INT NULL,
  `Nº administrativos` INT NULL,
  `Palmarés` INT NULL,
  `Presupuestos` FLOAT NULL,
  `Patrocinador` VARCHAR(45) NULL,
  PRIMARY KEY (`Código club`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`COMPETICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`COMPETICION` (
  `Código competición` VARCHAR(45) NOT NULL,
  `Nombre competición` VARCHAR(45) NOT NULL,
  `País` VARCHAR(45) NOT NULL,
  `Deporte` VARCHAR(45) NOT NULL,
  `Nº equipos` INT NULL,
  `Bonus económico` FLOAT NULL,
  PRIMARY KEY (`Código competición`),
  UNIQUE INDEX `Código competición_UNIQUE` (`Código competición` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`EQUIPO` (
  `Código equipo` VARCHAR(45) NOT NULL,
  `Código club` VARCHAR(45) NOT NULL,
  `Nombre equipo` VARCHAR(45) NOT NULL,
  `Estadio` VARCHAR(45) NOT NULL,
  `Localización` VARCHAR(45) NOT NULL,
  `Liga` VARCHAR(45) NOT NULL,
  `Categoría` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Presupuesto` FLOAT NULL,
  `Nº trofeos` INT NULL,
  `Nº técnicos` INT NULL,
  `Nº jugadores` INT NULL,
  `Capitán` VARCHAR(45) NULL,
  `Tipo deporte` VARCHAR(45) NOT NULL,
  `ID filial` VARCHAR(45) NULL,
  PRIMARY KEY (`Código equipo`, `Código club`),
  INDEX `cod_filial_idx` (`ID filial` ASC),
  CONSTRAINT `cod_club`
    FOREIGN KEY (`Código club`)
    REFERENCES `futbol`.`CLUB` (`Código club`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_filial`
    FOREIGN KEY (`ID filial`)
    REFERENCES `futbol`.`EQUIPO` (`Código equipo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`JUGADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`JUGADORES` (
  `Código identificador` VARCHAR(45) NOT NULL,
  `Código equipo` VARCHAR(45) NOT NULL,
  `Tipo identificación` VARCHAR(45) NOT NULL,
  `Nombre personal` VARCHAR(45) NOT NULL,
  `Dorsal` INT NOT NULL,
  `Posición` VARCHAR(45) NOT NULL,
  `Valor de mercado` FLOAT NOT NULL,
  `Nombre equipo` VARCHAR(45) NOT NULL,
  `Salario anual` FLOAT NOT NULL,
  PRIMARY KEY (`Código identificador`),
  INDEX `cod_ej_idx` (`Código equipo` ASC),
  CONSTRAINT `cod_ej`
    FOREIGN KEY (`Código equipo`)
    REFERENCES `futbol`.`EQUIPO` (`Código equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`SUBVENCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`SUBVENCION` (
  `Código subvención` VARCHAR(45) NOT NULL,
  `Importe` FLOAT NOT NULL,
  `Benefactor` VARCHAR(45) NOT NULL,
  `Tiempo invertido necesario (Horas)` INT NOT NULL,
  PRIMARY KEY (`Código subvención`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`ACTIVIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`ACTIVIDAD` (
  `Código actividad` VARCHAR(45) NOT NULL,
  `Tipo actividad` VARCHAR(45) NOT NULL,
  `Tiempo invertido (Horas)` INT NOT NULL,
  PRIMARY KEY (`Código actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`CUERPO_TECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`CUERPO_TECNICO` (
  `Código identificador` VARCHAR(45) NOT NULL,
  `Código equipo` VARCHAR(45) NOT NULL,
  `Tipo identificación` VARCHAR(45) NOT NULL,
  `Nombre personal` VARCHAR(45) NOT NULL,
  `Rol` VARCHAR(45) NOT NULL,
  `Nombre equipo` VARCHAR(45) NOT NULL,
  `Salario anual` FLOAT NOT NULL,
  PRIMARY KEY (`Código identificador`),
  INDEX `cod_ec_idx` (`Código equipo` ASC),
  CONSTRAINT `cod_ec`
    FOREIGN KEY (`Código equipo`)
    REFERENCES `futbol`.`EQUIPO` (`Código equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`EQUIPO_PARTICIPA_COMPETICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`EQUIPO_PARTICIPA_COMPETICION` (
  `Año disputado` INT NOT NULL,
  `Código competición` VARCHAR(45) NOT NULL,
  `Código equipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Año disputado`, `Código competición`, `Código equipo`),
  INDEX `cod_e_idx` (`Código equipo` ASC),
  CONSTRAINT `cod_participa`
    FOREIGN KEY (`Código equipo`)
    REFERENCES `futbol`.`EQUIPO` (`Código equipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cod_pg`
    FOREIGN KEY (`Código competición`)
    REFERENCES `futbol`.`COMPETICION` (`Código competición`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`EQUIPO_GANA_COMPETICION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`EQUIPO_GANA_COMPETICION` (
  `Año disputado` INT NOT NULL,
  `Código competición` VARCHAR(45) NOT NULL,
  `Código equipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Año disputado`, `Código competición`),
  INDEX `cod_e_idx` (`Código equipo` ASC),
  CONSTRAINT `cod_gana`
    FOREIGN KEY (`Código equipo`)
    REFERENCES `futbol`.`EQUIPO` (`Código equipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cod_eg`
    FOREIGN KEY (`Código competición`)
    REFERENCES `futbol`.`COMPETICION` (`Código competición`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`CLUB_RECIBE_SUBVENCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`CLUB_RECIBE_SUBVENCION` (
  `Código subvención` VARCHAR(45) NOT NULL,
  `Código club` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código club`, `Código subvención`),
  INDEX `cod_sub_idx` (`Código subvención` ASC),
  CONSTRAINT `cod_sub`
    FOREIGN KEY (`Código subvención`)
    REFERENCES `futbol`.`SUBVENCION` (`Código subvención`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cod_sclub`
    FOREIGN KEY (`Código club`)
    REFERENCES `futbol`.`CLUB` (`Código club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futbol`.`CLUB_REALIZA_ACTIVIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `futbol`.`CLUB_REALIZA_ACTIVIDAD` (
  `Código actividad` VARCHAR(45) NOT NULL,
  `Código club` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código actividad`, `Código club`),
  INDEX `cod_aclub_idx` (`Código club` ASC),
  CONSTRAINT `cod_act`
    FOREIGN KEY (`Código actividad`)
    REFERENCES `futbol`.`ACTIVIDAD` (`Código actividad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `cod_aclub`
    FOREIGN KEY (`Código club`)
    REFERENCES `futbol`.`CLUB` (`Código club`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
